version: "3.8"
services:
  backend:
    build:
      context: ./backend  # Asegúrate de que esto apunta al directorio donde está tu Dockerfile del backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
